### PR TITLE
Update test matrix to check PHP7.4

### PR DESCRIPTION
**Pull request by shulard**

### CODE REVIEW

**Comment by shulard** [comment]
@drupol, @jaylinski, I got a weird error on Travis... I don't know if it's related to latest code sniff updates or something else but the code I introduced here don't seems to touched that part.

Have you already encountered that ?

```
proc_open() expects parameter 1 to be string, array given
```

cf: https://travis-ci.com/friends-of-phpspec/phpspec-code-coverage/jobs/273513142

**Comment by jaylinski** [comment]
@shulard This error is really weird... I have no idea why this happens.

What I found out: the `deps=low` tests do not work as intendend.
```
before_script:
    - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; fi
```
is executed before the `script` part.

In the `script` part we run `composer update` again, which updates the installed packages to the latest version.

I'll open a PR to fix this. Maybe it helps...

**Comment by jaylinski** [comment]
@shulard I fixed it in #22. Please review.

**Comment by shulard** [comment]
Awesome ! I close this PR since everything will be addressed in the #22 ^^

**Pull request closed without merging**
