### PR TITLE
Switch to GitHub actions

### PR DESCRIPTION
**Pull request by drupol**
This PR:

* [x] Remove Travis configuration file and use Github Actions.
* [x] Remove PHPStan configuration file and fix phpdoc issues.

### CODE REVIEW

**Comment by drupol** [comment]
@jaylinski @shulard Any idea on how we could fix this ?

**Comment by shulard** [comment]
Hello @drupol !

I don't understand what need to be fixed here ^^. Also, I don't see where the Github action is run against that PR…

**Comment by drupol** [comment]
Hi @shulard ,

Find the Github Actions running here on my fork: https://github.com/drupol/phpspec-code-coverage/actions

I'm unable to fix the issue with php 7.2 low deps.

Any hint on how I could fix this ?

**Comment by shulard** [comment]
I guess it's be related to GitHub's API rate limiting… I saw that you are installing latest-deps then in another step downgrading to lowest-deps. Can't we directly install the lowest when required ? Because it may trigger a lot of duplicated API calls to GitHub... Not sure it'll fix the issue but I'm sure it'll limit the calls…

**Comment by drupol** [comment]
I think installing normally the deps, then updating using lower deps is the proper way to go.

I will try to do that in one step. brb

**Comment by drupol** [comment]
Yep, indeed, the `--prefer-lowest` option only exist on the `update` command of composer, so it must be done in 2 steps. First `install`, then `update`.

**Comment by jaylinski** [comment]
Nice PR. :+1:

Please squash your commits to a single commit.

**Comment by drupol** [comment]
@jaylinski I squashed the two last commits in the third commit.

I would prefer keeping separated commits in the branch until it's done and squashing at the end, we can even do it withing Github upon merging. Is it ok for you ?

**Comment by jaylinski** [comment]
@drupol As long as there are now WIP commits, it's fine for me. :slightly_smiling_face:

**Comment by shulard** [comment]
Hello !

Since we just merged #26 there is some conflicts here. @drupol, can you fix them ? Then we'll review and merge the github action configuration.

**Comment by drupol** [comment]
definitely!

**Comment by drupol** [comment]
@shulard Waiting for your feedback on this :-)

**Comment by shulard** [comment]
Wow sorry I totally missed it ^^

If course it's ok for me too, I just merged it.

**Pull request merged**
