### PR TITLE
Execute tests against PHP8.3 and allow compatibility with phpunit/php-code-coverage v11.*

### PR DESCRIPTION
**Pull request by shulard**
Just updated the CI configuration to test against PHP8.3 and refine some composer dependencies rules.

### CODE REVIEW

**Comment by shulard** [comment]
@jaylinski it looks like the `phpunit/php-spec-coverage` package doesn't expose some methods anymore in version 11.*: https://github.com/sebastianbergmann/php-code-coverage/blob/11.0.1/ChangeLog-11.0.md

Do you think it's relevant to support v11 today ? Maybe I must split this PR in two distinct ones (one for PHP and one for PHPUnit upgrade…).

**Review by jaylinski — CHANGES_REQUESTED** [review]
I think we should support v11. Seems we only have to use the `includeFiles()`-method instead (or add it on our own).

https://github.com/sebastianbergmann/php-code-coverage/commit/8fdb7ff2840fee629acb159ac266a7718bbf1beb

Do you wanna fix it? I can do it too.

**Comment by shulard** [comment]
I already started working on the change. 

My main concern is that we can't have a the `blacklist` and `blacklist_files` options anymore. The change regarding `include` is pretty straightforward but the `exclude` can't be implemented anymore. I don't know if it's a big deal or not (I don't use any exclude on my side…).

**Comment by jaylinski** [comment]
> I already started working on the change.
> 
> My main concern is that we can't have a the `blacklist` and `blacklist_files` options anymore. The change regarding `include` is pretty straightforward but the `exclude` can't be implemented anymore. I don't know if it's a big deal or not (I don't use any exclude on my side…).

That is true, I didn't notice that there is now workaround for the `exclude*`-functions. Can we implement it ourselves by only including files that are not in the excludes-list? :thinking: 

I'm also not opposed to dropping the `blacklist`-feature and doing a new major release (and also dropping EOL PHP versions).

**Comment by balazscsaba2006** [comment]
Hi there. Any update on this PR?

**Comment by shulard** [comment]
Hello !

Sorry, nothing new here, I hadn't time to work on that part yet…

**Review by jaylinski — APPROVED** [review]

**Pull request merged**
