### PR TITLE
Various forgotten minor changes

### PR DESCRIPTION
**Pull request by drupol**

### CODE REVIEW

**Comment by jaylinski** [comment]
I also noticed we are no longer testing with `--prefer-lowest` (Composer).

(Maybe you want to add it again, but it's fine for me if we keep the tests as they are now.)

**Comment by drupol** [comment]
Let's do that in a follow up :-)

**Comment by shulard** [comment]
So it's ready to merge here ? It'll fix the failing build on master ?

**Comment by drupol** [comment]
yes it's ready :-)

**Pull request merged**
