### PR TITLE
External services configuration

### PR DESCRIPTION
**Pull request by shulard**
This PR:

* [x] Update and composer.json file.
* [x] Update Travis configuration #4.
* [x] Update Scrutinizer configuration.

Currently, the code sniffer is disabled, we need to decided which one to use :smile:.

### CODE REVIEW

**Comment by shulard** [comment]
@drupol, I've splitted the commits from #10 to merge the external services configuration at first. Are you ok to merge this one, then we continue looking at the coding style ?

**Comment by drupol** [comment]
Yes I do agree. However, I would normalize the composer.json file.

**Comment by shulard** [comment]
@drupol the composer.json file has been updated before merging.

**Comment by drupol** [comment]
Nice nice !

**Pull request merged**
