### PR TITLE
Allow for phpunit/php-code-coverage ^9.0

### PR DESCRIPTION
**Pull request by pamil**

### CODE REVIEW

**Comment by shulard** [comment]
Hello @pamil !

Thank you for the PR. It seems that phpunit/php-code-coverage v9 has some method and object signatures updates. Can you upgrade the code regarding these change ?

**Comment by pamil** [comment]
@shulard sure thing, I can take care of it next week :)

**Comment by shulard** [comment]
hello @pamil, @jaylinski just finalized the update in a new PR (#39). A new release will be published soon (v6.x) with those updates !

**Comment by pamil** [comment]
Thanks a lot, @shulard :)

**Pull request closed without merging**
