### PR TITLE
Allow for phpspec ^7.0

### PR DESCRIPTION
**Pull request by pamil**

### CODE REVIEW

**Comment by pamil** [comment]
The failure seems not related to the PR changes.

**Comment by jaylinski** [comment]
We may have to drop PHP 7.1 support in order to support this.

**Comment by pamil** [comment]
@jaylinski I've sent #37 doing that, should be green in a minute

**Comment by shulard** [comment]
Hello !

I think that we need to tag a version before dropping PHP7.1 (see #32).

**Comment by shulard** [comment]
@pamil, since we merged #37, can you rebase this one before we merge it ?

**Pull request merged**
